module.exports = {
    messageTypeInfo: "info",
    messageTypeWarning: "warning",
    messageTypeSuccess: "success",
    messageTypeDanger: "danger",
    saveData: "Saved Successfully.",
    updateData: "Updated Successfully.",
    deleteData: "Deleted Successfully.",
    addData: "Added Successfully.",
    editData: "Edited Successfully.",
    removeData: "Removed Successfully.",
    saveDataFail: "Couldn't Saved Successfully.",
    updateDataFail: "Couldn't Updated Successfully.",
    deleteDataFail: "Couldn't Deleted Successfully.",
    addDataFail: "Couldn't Added Successfully.",
    editDataFail: "Couldn't Edited Successfully.",
    removeDataFail: "Couldn't Removed Successfully.",
    filesUploaded :  "Files Uploaded Successfully.",
    filesUploadedFail :  "Files Couldn't Uploaded Successfully.",
    filesNoSelected :  "No Files Selected.",
    filesAlreadyExists :  "Already Exists. Files Couldn't Uploaded Successfully.",
    nameAlreadyExists :  "Name already taken. Please choose another name.",
    urlAlreadyExists :  "Url already taken. Please choose another url.",
    alreadyExists :  "Already Exists.",
    alreadyAdded :  "Already added one, So you can edit that one.",
    success: "Successfully.",
    info: "Please contact your system admin.",
    warning: "Please contact your system admin.",
    error: "We are facing some problem while processing the current request. Please try again later.",
    unhandledError: "We are facing some problem while processing the current request. Please try again later.",
    unAuthenticated: "You are not authenticated user.",
    nullError: "Requested object could not found.",
    nullReferenceExceptionError: "There are one or more required fields that are missing.",
    isEmailExists :  "Email already taken. Please choose another email.",
    isEmailNotExists :  "Email is not taken.",
    dataNotFound: 'Data not found.',
    tokenExpired: 'Token expired.',
    unAuthorized: 'You are not authorized user.',
    logout: 'Logout Successfully.',
    databaseCreate: "Created Database Successfully.",
    databaseCreateFail: "Couldn't Created Database Successfully.",
    tableCreate: "Created Table Successfully.",
    tableCreateFail: "Couldn't Created Table Successfully.",
    tableDelete: "Deleted Table Successfully.",
    tableDeleteFail: "Couldn't Deleted Table Successfully.",
    tableInsert: "Inserted Data Successfully.",
    tableInsertFail: "Couldn't Inserted Data Successfully.",
}