version=0.1
   [default.deploy.parameters]
    stack_name = "PIDIROPStack-3"
    region = "us-east-1"
    confirm_changeset = true
    s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-spwrpzafu1wq"
    s3_prefix = "PIDIROPStack-3"
    capabilities = "CAPABILITY_IAM"
 image_repositories = []

[dev]
[dev.deploy]
[dev.deploy.parameters]
 stack_name = "pd3"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-spwrpzafu1wq"
 s3_prefix = "pd3"
 region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
